int16 id
float64 Nose_x
float64 Nose_y
float64 LEye_x
float64 LEye_y
float64 REye_x
float64 REye_y
float64 LEar_x
float64 LEar_y
float64 REar_x
float64 REar_y
float64 LShoulder_x
float64 LShoulder_y
float64 RShoulder_x
float64 RShoulder_y
float64 LElbow_x
float64 LElbow_y
float64 RElbow_x
float64 RElbow_y
float64 LWrist_x
float64 LWrist_y
float64 RWrist_x
float64 RWrist_y
float64 LHip_x
float64 LHip_y
float64 RHip_x
float64 RHip_y
float64 LKnee_x
float64 LKnee_y
float64 Rknee_x
float64 Rknee_y
float64 LAnkle_x
float64 LAnkle_y
float64 RAnkle_x
float64 RAnkle_y
float64 Neck_x
float64 Neck_y





