bool left   		# object is to the left of another from robot's perspective
bool right  		# object is to the right of another from robot's perspective
bool above  		# object is above another
bool below  		# object is below another
bool behind 		# object is behind another from robot's perspective
bool frontof 		# object is in front of another from robot's perspective
bool near   		# object is near another object
bool not_near		# object is not near another object
bool left_most 		# object furthest to the left of the robot based on the angle from the robot's perspective
bool right_most 	# object further to the right of the robot based on the angle from the robot's perspective
